[package]
name = "sidechain"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
argh = "0.1.13"
blake3 = "1.8.3"
env_logger = "0.11.8"
log = "0.4.29"
rayon = "1.11.0"
rusqlite = "0.38.0"
walkdir = "2.5.0"
